### PR TITLE
Update README to reflect production usage

### PR DESCRIPTION
**Pull request by MidasLamb**
We've finalized our auth refactor and have been running OpenFGA in production for a few weeks now.

### CODE REVIEW

**Review by craigpastro — APPROVED** [review]
Hi @MidasLamb! That's very exciting. Please keep us updated on your experience running in production. Thank you!

**Review by jon-whit — APPROVED** [review]

**Comment by jon-whit** [comment]
@MidasLamb by chance, have you had any issues with connections disconnecting frequently with the MySQL storage adapter?

**Comment by MidasLamb** [comment]
@jon-whit , not that I've noticed, it's been running without a hitch. I've also not really looked into that to see if that's occurring transparently  maybe.

**Comment by jon-whit** [comment]
@MidasLamb would you mind observing that over the next week or two and report back? I'd love to know if that's happening in your production environment in OpenFGA.

**Comment by MidasLamb** [comment]
I'll try to keep an eye on it!

**Comment by MidasLamb** [comment]
@jon-whit , going through the openfga logs, I do see this quite a few times:
```
[mysql] 2023/01/30 12:12:29 connection.go:360: invalid connection
[mysql] 2023/01/30 12:12:29 connection.go:360: invalid connection
[mysql] 2023/01/30 12:12:29 connection.go:360: invalid connection
```

**Comment by aaguiarz** [comment]
@MidasLamb would it be possible for you to add your company to the list here https://github.com/openfga/community/blob/main/ADOPTERS.MD?  Thanks!

**Pull request merged**
