### PR TITLE
fix: inject typesystem into context in benchmarks

### PR DESCRIPTION
**Pull request by jon-whit**
## Description
This fixes the ListObjects benchmarks by injecting the needed `typesystem` into the context before calling `Execute`.

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by miparnisari** [comment]
how did this break? this is passing on the latest `main`

**Comment by adriantam** [comment]
> how did this break? this is passing on the latest `main`: https://github.com/openfga/openfga/actions/runs/4359615923/jobs/7621593177

Main also broke - https://github.com/openfga/openfga/actions/runs/4359615923/jobs/7621593177#step:5:42
Unfortunately it does not mark as fail on CICD

**Review by adriantam — APPROVED** [review]

**Comment by miparnisari** [comment]
> Main also broke - https://github.com/openfga/openfga/actions/runs/4359615923/jobs/7621593177#step:5:42
Unfortunately it does not mark as fail on CICD

@adriantam can you mark it as fail please?

**Comment by jon-whit** [comment]
> 🤦‍♀️ @adriantam can you mark it as fail please?
@adriantam @miparnisari please don't mark the bench workflow as required, because it takes 10+ minutes. This will kill our PR CI/CD responsiveness. That workflow was meant to be a reviewable artifact but not a blocker for PR merges.

**Comment by jon-whit** [comment]
> I don't understand what the 10 minutes have to do with it. The step will run no matter what, i'm saying we should fail the workflow if the return code is non-zero. Otherwise how are we going to detect problems?

I think we're not communicating clearly here.. I don't want to wait 10 minutes every PR build to finish waiting on the benchmark stage. If we can fail the benchmark workflow but not require it to pass, then that's fine. But let's not make it a required build stage to pass.

**Pull request merged**
