### PR TITLE
fix: dependency declaration in Docker-compose.yaml

### PR DESCRIPTION
**Pull request by miparnisari**
## Description

Create `docker-compose.dev.yaml`.

```
[7/07/23 12:14:08] ~/GitHub/openfga (docker-compose-deps) $ docker compose -f .docker/docker-compose.yaml -f .docker/docker-compose.dev.yaml up
[+] Building 0.0s (0/0)                                                                                                                                                                                                                    
[+] Running 8/8
 ✔ Network openfga-dev_default         Created                                                                                                                                                                                        0.1s 
 ✔ Container otel-collector            Created                                                                                                                                                                                        0.1s 
 ✔ Container postgres                  Created                                                                                                                                                                                        0.2s 
 ✔ Container openfga-dev-prometheus-1  Created                                                                                                                                                                                        0.1s 
 ✔ Container jaeger                    Created                                                                                                                                                                                        0.2s 
 ✔ Container migrate                   Created                                                                                                                                                                                        0.2s 
 ✔ Container openfga-dev-grafana-1     Created                                                                                                                                                                                        0.1s 
 ✔ Container openfga                   Created                                                                                                                                                                                        0.1s 
Attaching to jaeger, migrate, openfga, openfga-dev-grafana-1, openfga-dev-prometheus-1, otel-collector, postgres

```


## References
https://docs.docker.com/compose/extends/#multiple-compose-files

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by adriantam** [comment]
Do we need to update https://openfga.dev/docs/getting-started/setup-openfga/docker#profiler-pprof?

**Comment by miparnisari** [comment]
> Do we need to update https://openfga.dev/docs/getting-started/setup-openfga/docker#profiler-pprof?

Nope, that instruction `docker run -p 8080:8080 -p 8081:8081 -p 3000:3000 -p 3001:3001 openfga/openfga run --profiler-enabled` uses the Docker image directly, not the docker-compose file in this repo

**Review by rhamzeh — COMMENTED** [review]
Maybe starting grafana too is a good idea?

**Comment by miparnisari** [comment]
> Maybe starting grafana too is a good idea?

👍 

> Note: If you want to push a development docker-compose, what some projects do is have a folder containing:
> 
> * Containerfile/Dockerfile # prod
> * dev.Containerfile/dev.Dockerfile # dev
> * docker-compose.yaml # prod
> * docker-compose.dev.yaml # dev

I like this idea, i'll try this out. Because the other thing that has been bothering me is that, when developing locally, I need to remember to change

```
openfga:
    image: openfga/openfga:latest
```

to 

```
openfga:
    build: .
```

**Comment by miparnisari** [comment]
Holy cow, moving Docker files around is not as easy as I thought.

**Comment by adriantam** [comment]
> > Do we need to update https://openfga.dev/docs/getting-started/setup-openfga/docker#profiler-pprof?
> 
> Nope, that instruction `docker run -p 8080:8080 -p 8081:8081 -p 3000:3000 -p 3001:3001 openfga/openfga run --profiler-enabled` uses the Docker image directly, not the docker-compose file in this repo

There is a tab for docker-compose.yml

Screenshot 2023-07-07 at 3 54 43 PM

**Comment by miparnisari** [comment]
> > > Do we need to update https://openfga.dev/docs/getting-started/setup-openfga/docker#profiler-pprof?
> > 
> > 
> > Nope, that instruction `docker run -p 8080:8080 -p 8081:8081 -p 3000:3000 -p 3001:3001 openfga/openfga run --profiler-enabled` uses the Docker image directly, not the docker-compose file in this repo
> 
> There is a tab for docker-compose.yml
> 
> Screenshot 2023-07-07 at 3 54 43 PM


> There is a tab for docker-compose.yml

Oh. Yeah that's fine, it only has 3 containers with none of the observability stuff.

**Comment by miparnisari** [comment]
I just noticed that `docker compose -f .docker/docker-compose.yaml -f .docker/docker-compose.dev.yaml up` doesn't actually cause a `build`. It uses the `image` and there is no way to override this :(

**Pull request closed without merging**
