### PR TITLE
style: enable gci and gofumpt linters

### PR DESCRIPTION
**Pull request by tranngoclam**
## Description

- Enable `gci` (stricter imports ordering) and `gofumpt` instead of `goimports`.

## References

https://github.com/golangci/golangci-lint/issues/1490

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by jon-whit** [comment]
@tranngoclam any reason why you prefer `gofumpt` over `goimports`? Are there some strong objective reasons, or is it more just subjective preference? 

@openfga/backend we need to set `gofumpt` or `goimports` as the standard and communicate that clearly, and we should generally document some linter standards for other rules.

**Review by jon-whit — CHANGES_REQUESTED** [review]
Requested feedback on standard go import linter. Let's resolve that discussion before merging this.

**Comment by tranngoclam** [comment]
> @tranngoclam any reason why you prefer `gofumpt` over `goimports`? Are there some strong objective reasons, or is it more just subjective preference?
> 
> @openfga/backend we need to set `gofumpt` or `goimports` as the standard and communicate that clearly, and we should generally document some linter standards for other rules.

@jon-whit The `goimports` is replaced by `gci` (https://github.com/daixiang0/gci) and the `gofmt` is replaced by `gofumpt` (https://github.com/mvdan/gofumpt). Both new linters are stricter than the old ones

- With gci, we can order all imports and group them into the groups we define (goimports is unable to group the packages if they are not closely placed)
- With gofumpt, we can see all of the supported features here: https://github.com/mvdan/gofumpt?tab=readme-ov-file#added-rules

**Review by miparnisari — DISMISSED** [review]
I am okay with this change, but please fix all the merge conflicts. :)

**Comment by tranngoclam** [comment]
> I am okay with this change, but please fix all the merge conflicts. :)

Thankd @miparnisari, I have resolved all conflicts

**Comment by miparnisari** [comment]
@jon-whit are you OK with merging this?

**Comment by curfew-marathon** [comment]
Thank you for your contribution.  Despite the conversation, we took this back to the team and discussed our stance on tooling.  At this time we would like to keep to the standard go toolchain and will not move forward with gci and gofumpt.  Apologies for the churn and in the future if you have any other style suggestions let's discuss first.  Thank you for sparking a conversation around our standards!

**Pull request closed without merging**
