### PR TITLE
fix: Update signal handling in Run function

### LINKED ISSUE #1910: Connection closed abruptly because of SIGTERM is not handled.
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

When restarting OpenFGA, our server experiencing forced connection close.
When OpenFGA receives SIGTERM signal it continue processing ongoing requests and shutdown only when nothing left.
SIGTERM should also added to handled signals at [code](https://github.com/openfga/openfga/blob/v1.6.1/cmd/run/run.go#L438)

Kubernetes sends SIGTERM on graceful termination period. [link](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination)
> Typically, with this graceful termination of the pod, kubelet makes requests to the container runtime to attempt to stop the containers in the pod by first sending a TERM (aka. SIGTERM) signal, with a grace period timeout, to the main process in each container.

originally from https://github.com/openfga/openfga/issues/1909

### OpenFGA version

v1.6.0

### How are you running OpenFGA?

In Kubernetes

### What datastore are you using?

MySQL

### OpenFGA Flags

no

### Logs

upstream connect error or disconnect/reset before headers. reset reason: connection termination

dev.openfga.sdk.errors.FgaApiInternalError: check

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

This pull request updates the signal handling in the `Run` function to include the `SIGTERM` signal in addition to `SIGINT` and `SIGKILL`. This ensures that the server can gracefully terminate when receiving a `SIGTERM` signal.

## References

fixes #1910

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
We will have to add `Skip-changelog` again 🫠

**Comment by senojj** [comment]
I'm surprised that SIGTERM wasn't being bound already. Good catch.

**Review by jpadilla — APPROVED** [review]
thank you!

**Comment by miparnisari** [comment]
> I'm surprised that SIGTERM wasn't being bound already. Good catch.

That was me, oops! https://github.com/openfga/openfga/pull/1928#issuecomment-2349047652

**Review by miparnisari — APPROVED** [review]

**Comment by senojj** [comment]
> @senojj That was me, oops! https://github.com/openfga/openfga/commit/f10d8e5df8e3d0ecfcd91a4e1a772dab32d8d360

@miparnisari we never go alone, this was a group effort 😄

**Pull request merged**
