### PR TITLE
docs: update security-self-assessment.md

### PR DESCRIPTION
**Pull request by lj365**
- Basic Threat Landscape 
- Secure Development Practices improved with status badges
- all-around fixes

## Review Checklist
- [ ] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Review by adriantam — APPROVED** [review]

**Comment by miparnisari** [comment]
does this supersede https://github.com/openfga/openfga/pull/1206 ?

**Comment by lj365** [comment]
> does this supersede #1206 ?

It does. I have incorporated suggestions. The source of truth for self-assessments seems to be the cncf/tag-security repository.

**Comment by miparnisari** [comment]
image

Hmmm, did I mess something up by closing https://github.com/openfga/openfga/pull/1206?

**Comment by aaguiarz** [comment]
BTW, we should delete this one instead of updating it here, right? the assessment will live here https://github.com/cncf/tag-security/pull/1235

**Review by miparnisari — APPROVED** [review]

**Comment by aaguiarz** [comment]
We should close this PR :) we are handling it here https://github.com/cncf/tag-security/pull/1235

**Pull request merged**
