### PR TITLE
test: ignore goleak for mysql driver

### PR DESCRIPTION
**Pull request by adriantam**
## Description
Occasionally test fails due to perceived leak in mysql driver. However, in reality it is just sometimes the driver is slow in deallocating its threads.  Thus, we can safely ignore these "leaks".

This happens when running test with OpenFGA locally.  It errors with the following traces:

```
--- FAIL: TestListUsersMySQL (11.84s)
    tests.go:62: creating connection to address 0.0.0.0:55506
    testutils.go:206: 2024-06-26 10:08:01.229569 -0400 EDT m=+15.947387210 not serving yet at address 0.0.0.0:55506 rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 0.0.0.0:55506: connect: connection refused"
    testutils.go:206: 2024-06-26 10:08:01.925779 -0400 EDT m=+16.643592043 not serving yet at address 0.0.0.0:55506 rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 0.0.0.0:55506: connect: connection refused"
    tests.go:56: waiting for server to stop
    tests.go:59: server stopped with error:  <nil>
    listusers_test.go:44: found unexpected goroutines:
        [Goroutine 56354 in state select, with github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1 on top of the stack:
        github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()
        	/Users/adrian.tam/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.1/connection.go:628 +0xb0
        created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher in goroutine 56341
        	/Users/adrian.tam/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.1/connection.go:625 +0x1b4
         Goroutine 53368 in state select, with github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1 on top of the stack:
        github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()
        	/Users/adrian.tam/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.1/connection.go:628 +0xb0
        created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher in goroutine 53381
        	/Users/adrian.tam/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.1/connection.go:625 +0x1b4
         Goroutine 54548 in state select, with github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1 on top of the stack:
        github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()
        	/Users/adrian.tam/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.1/connection.go:628 +0xb0
        created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher in goroutine 54533
        	/Users/adrian.tam/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.1/connection.go:625 +0x1b4
         Goroutine 52807 in state select, with github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1 on top of the stack:
        github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()
        	/Users/adrian.tam/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.1/connection.go:628 +0xb0
        created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher in goroutine 53112
        	/Users/adrian.tam/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.1/connection.go:625 +0x1b4
        ]
``` 

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Review by elbuo8 — APPROVED** [review]

**Review by miparnisari — CHANGES_REQUESTED** [review]
I'm not sure about this change. I have never seen this leak before I went on vacation. Have you seen this leak before june 12? 😆 

In your description you say that the leak was seen in `TestListUsersMySQL`. Are you sure it was not introduced by a recent commit? For example this one? https://github.com/openfga/openfga/pull/1714/files, specifically this line `cfg.ListUsersDeadline = 6 * time.Second` (cc @willvedd)

I'm not sure that line fixes the problem, see https://github.com/openfga/openfga/pull/1714/files#r1656450644

**Comment by adriantam** [comment]
> I'm not sure about this change. I have never seen this leak before I went on vacation. Have you seen this leak before june 12? 😆
> 
> In your description you say that the leak was seen in `TestListUsersMySQL`. Are you sure it was not introduced by a recent commit? For example this one? https://github.com/openfga/openfga/pull/1714/files, specifically this line `cfg.ListUsersDeadline = 6 * time.Second` (cc @willvedd)
> 
> I'm not sure that line fixes the problem, see https://github.com/openfga/openfga/pull/1714/files#r1656450644

The trace is an example of the claimed leak and we see this while working on [optimizing userset check](https://github.com/openfga/openfga/tree/feat/userset_quick_check).  The question is that given we never create connection in the test outside of test  infrastructure, is this something we should be concerned?

**Comment by jpadilla** [comment]
```
--- FAIL: TestListObjectsMySQL (12.64s)
    tests.go:62: creating connection to address 0.0.0.0:54103
    testutils.go:206: 2024-06-28 05:44:30.816267 -0400 EDT m=+21.775927334 not serving yet at address 0.0.0.0:54103 rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 0.0.0.0:54103: connect: connection refused"
    testutils.go:206: 2024-06-28 05:44:31.475118 -0400 EDT m=+22.434780543 not serving yet at address 0.0.0.0:54103 rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 0.0.0.0:54103: connect: connection refused"
    tests.go:56: waiting for server to stop
    tests.go:59: server stopped with error:  <nil>
    listobjects_test.go:28: found unexpected goroutines:
        [Goroutine 123293 in state select, with github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1 on top of the stack:
        github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()
        	/Users/jose.padilla/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.1/connection.go:628 +0xb0
        created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher in goroutine 123377
        	/Users/jose.padilla/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.1/connection.go:625 +0x1b4
        ]
FAIL
```

**Comment by miparnisari** [comment]
> The question is that given we never create connection in the test outside of test infrastructure, is this something we should be concerned?

@adriantam until I know the root cause I am slightly concerned, which is why I don't want to ignore the leak. It's probably a flaw in our test code, but i don't know

**Pull request closed without merging**
