### PR TITLE
fix http otel trace propagation

### PR DESCRIPTION
**Pull request by Zach-Johnson**
## Description

This PR adds proper otel trace context propagation to the grpc-gateway http server that open fga runs.
Previously, the grpc-gateway http server was not propagating the trace context to the grpc server, which caused the trace context to be lost when the request was forwarded to the grpc server.
This resolves the issue opened in https://github.com/openfga/openfga/pull/1024

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by Zach-Johnson** [comment]
Hi, is it possible to get a review on this please?

**Comment by rhamzeh** [comment]
Sorry for the delay @Zach-Johnson - we'll take a look

**Comment by jon-whit** [comment]
@Zach-Johnson would you please provide a sample snippet used to demonstrate before/after?

**Comment by Zach-Johnson** [comment]
Sure, @jon-whit -

`main.go`
```
package main

import (
	"context"
	"log"
	"net/http"
	"time"

	openfga "github.com/openfga/go-sdk"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

func main() {
	cleanup := initTracerAuto()
	defer cleanup(context.Background())

	fgaClient := openfga.NewAPIClient(&openfga.Configuration{
		HTTPClient: &http.Client{Timeout: 10 * time.Second, Transport: otelhttp.NewTransport(http.DefaultTransport)},
		ApiUrl:     "http://localhost:8080",
	})

	trace := otel.GetTracerProvider().Tracer("trace")
	ctx := context.Background()
	ctx, span := trace.Start(ctx, "example")
	_, _, err := fgaClient.OpenFgaApi.ListStores(ctx).Execute()
	if err != nil {
		log.Fatalln("failed", err)
	}
	defer span.End()
}

func initTracerAuto() func(context.Context) error {
	exporter, err := otlptrace.New(
		context.Background(),
		otlptracegrpc.NewClient(
			otlptracegrpc.WithInsecure(),
			otlptracegrpc.WithEndpoint("localhost:4317"),
		),
	)
	if err != nil {
		log.Fatalln("failed", err)
	}

	resources, err := resource.New(
		context.Background(),
		resource.WithAttributes(
			attribute.String("service.name", "otel-otlp-go-service"),
			attribute.String("application", "otel-otlp-go-app"),
		),
	)
	if err != nil {
		log.Fatalln("failed", err)
	}

	otel.SetTracerProvider(
		sdktrace.NewTracerProvider(
			sdktrace.WithSampler(sdktrace.AlwaysSample()),
			sdktrace.WithSpanProcessor(sdktrace.NewBatchSpanProcessor(exporter)),
			sdktrace.WithSyncer(exporter),
			sdktrace.WithResource(resources),
		),
	)

	otel.SetTextMapPropagator(
		propagation.NewCompositeTextMapPropagator(
			propagation.TraceContext{},
			propagation.Baggage{},
		),
	)

	return exporter.Shutdown
}
```

Then set up jaeger:
```
docker run --rm --name jaeger \
  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 4317:4317 \
  -p 4318:4318 \
  -p 14250:14250 \
  -p 14268:14268 \
  -p 14269:14269 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.57
```

And openfga:
```
go run ./cmd/openfga/ run --log-level debug --trace-enabled --trace-otlp-endpoint localhost:4317 --trace-sample-ratio 1.0
```

Then run the example program:
```
go run .
```

Pull up localhost:16686 to see the jaeger dash, the spans from the example will be connected to the openfga spans with this fix:
image

**Review by miparnisari — APPROVED** [review]

**Comment by miparnisari** [comment]
For comparison, this is how it looks on `main`:

image

**Pull request merged**
