### PR TITLE
CI: Add workflow to update NOTICE file

### LINKED ISSUE #1319: Automated process to update NOTICE file
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

We want to keep the NOTICE file up to date on every dependency change.

### Describe the ideal solution

Update [NOTICE](https://github.com/openfga/openfga/blob/main/NOTICE) file using some kind of automated process (Github actions?)

The file is in https://app.fossa.com/projects/git%2Bgithub.com%2Fopenfga%2Fopenfga

### Alternatives and current workarounds

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
## Description

This pull request updates the NOTICE file based on the FOSSA analysis. The FOSSA CLI is used to analyze the project and generate an updated NOTICE file. The changes include including unused dependencies and generating attribution information. For more details, please refer to the FOSSA analysis report at [FOSSA][1].

[1]: https://app.fossa.com/projects/git%2Bgithub.com%2Fopenfga%2Fopenfga

## Action items

- It requires `FOSSA_API_KEY` API token be to added and add them as secrets to be consumed by GitHub Action. (ref [docs](https://docs.fossa.com/docs/api-reference))

It requires a FOSSA subscription (see [ref](https://github.com/Siddhant-K-code/openfga/actions/runs/8316135416/job/22755235252#step:4:190))

image

## References

fixes #1319

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
Tests are failing, flaky? 🫠

**Comment by miparnisari** [comment]
I need to create a service account for OpenFGA so that we can create a token for it in FOSSA. Hang tight...

**Review by miparnisari — APPROVED** [review]

**Review by willvedd — APPROVED** [review]
Great work.

**Comment by Siddhant-K-code** [comment]
@willvedd, As you can see in [logs](https://github.com/openfga/openfga/actions/runs/8379924182/job/22947956041#step:4:13), issue is with permission, I would suggest to create PAT token from admin's account (so it has the correct permissions)

image

**Comment by miparnisari** [comment]
@Siddhant-K-code thanks for your reply. The token needed must be created in FOSSA, not Github. I already got in touch with FOSSA support :)

**Pull request merged**
