### PR TITLE
chore: add enable-consistency-params experimental flag

### PR DESCRIPTION
**Pull request by jimmyjames**
## Description

Adds the experimental flag `enable-consistency-params`, which will be used to enable the configuration of read consistency behavior.

Note that this PR targets the `stronger-consistency-options` branch, which we will work on as we implement this feature.

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by jimmyjames** [comment]
Not sure why the `govulncheck` is failing; error details don't seem to indicate anything changed in this PR

**Review by rhamzeh — DISMISSED** [review]

**Comment by jon-whit** [comment]
@jimmyjames don't forgot to add the experimental flag as an explicit const/enum.

See https://github.com/openfga/openfga/blob/ad754bde745078d9005ce4a2afbbb12e53929360/pkg/server/server.go#L54 for an example.

**Comment by jimmyjames** [comment]
> Not sure why the `govulncheck` is failing; error details don't seem to indicate anything changed in this PR 🤔. Maybe related to https://pkg.go.dev/vuln/GO-2024-2887

Rebased target branch to include #1669 which resolves `govulncheck`

**Comment by jimmyjames** [comment]
> @jimmyjames don't forgot to add the experimental flag as an explicit const/enum.
> 
> See
> 
> https://github.com/openfga/openfga/blob/ad754bde745078d9005ce4a2afbbb12e53929360/pkg/server/server.go#L54
> 
> for an example.

Added the const in this PR instead of the follow-on PR to use the enum.

**Review by rhamzeh — APPROVED** [review]

**Pull request merged**
